added banner to game
sivicstudio/starkludo pull request #32
Opened 2024-08-26 23:30 UTC by Solomonsolomonsolomon

Description:
Summary: I’ve added a new footer banner component called Footer.tsx to our game page. This footer is designed to always stay at the bottom of the screen, no matter how much content is on the page.

files Added: Footer.tsx and Footer.scss
Changes Made:

New Component: Created Footer.tsx to serve as our new footer banner.
Styling: Added custom styles to make sure the footer looks great and fits well with the existing design.
JS : Used js to ensure footer stays at bottom irrespective of screen size
Details:

Component Name: Footer.tsx
Why: The footer banner provides a more consistent navigation experience by sticking to the bottom of the screen.
Styling: Designed to blend seamlessly with the rest of the game page and adjusted for different screen sizes.
JavaScript Functionality: The footer is anchored to the bottom using fixed positioning so it stays visible at all times, enhancing usability.
Testing:

Checked the footer on various screen sizes to make sure it stays put at the bottom.
Ensured it doesn’t overlap with other content and resizes properly.
![Screenshot (182)](https://github.com/user-attachments/assets/d49d50c7-5e22-463f-8ea6-deb20eaae59a)
![Screenshot (183)](https://github.com/user-attachments/assets/ba5e9acb-2881-4c76-ba7e-002eafed67d9)

2024-08-31 23:26 UTC, vibenedict commented on client/pnpm-lock.yaml
please remove this file from pull request

2024-08-31 23:37 UTC, vibenedict commented
also add issue number this pr is closing in the pr description. e.g "Closes #<issue number>"

2024-09-01 06:19 UTC, Solomonsolomonsolomon commented
Thanks @vibenedict . i  I've made updates based on the feedback and would appreciate your review.

2024-09-01 06:49 UTC, Solomonsolomonsolomon commented on client/pnpm-lock.yaml
file removed in latest commit

2024-09-01 11:35 UTC, vibenedict requested changes

2024-09-01 11:35 UTC, vibenedict commented on client/src/assets/images/starknet.png
please use the logo from here: https://www.starknet.io/media-kit/

2024-09-01 11:35 UTC, vibenedict commented on client/pnpm-lock.yaml
It seems you deleted the file entirely which is preventing the app from building. What I meant was to revert the changes you made in the file.

Since you have already deleted it, I would suggest you just download the file from the `dev` branch, and commit it along with this PR.

@Solomonsolomonsolomon

2024-09-01 11:35 UTC, vibenedict commented on client/src/assets/images/starknet.png
@Solomonsolomonsolomon  please look into this

2024-09-01 16:01 UTC, Solomonsolomonsolomon commented
Sorry for the misunderstanding @vibenedict  , ive restored the file from origin/dev and i also changed the starknet logo to one from https://www.starknet.io/media-kit/ . Please inform me if there are any more changes

2024-09-01 21:20 UTC, vibenedict requested changes

2024-09-01 21:20 UTC, vibenedict commented on client/src/components/Footer.tsx
> +          Powered by Starknet{" "}
I don't think "Starknet" needs to still be here since it is already on the image

2024-09-01 21:20 UTC, vibenedict commented on client/src/components/Footer.tsx
> +          and Dojo Engine{" "}
Please remove the text "Dojo Engine" since the image already contains Dojo

2024-09-01 22:39 UTC, Solomonsolomonsolomon commented
Names Starknet and DojoEngine removed as their images are present

2024-09-02 07:12 UTC, vibenedict approved these changes
LGTM

2024-09-02 07:13 UTC, merged