Added change boards toggle
sivicstudio/starkludo pull request #47
Opened 2024-08-30 18:40 UTC by melnikga

I created a functionality for switching boards using context, as an example I added a "Texture" board where the usual colors are replaced with different textures, the form for switching boards is located in the toolbox window

2024-09-01 12:43 UTC, vibenedict reviewed
Hi @melnikga, great job here but the task is to be able to replace the entire board with another board. The board and the game pieces are not attached together, making it possible to make the board replaceable. 

To better understand the task, comment out `<LudoTiles/>` in [`Ludo.tsx`](https://github.com/sivicstudio/starkludo/blob/dev/client/src/components/Ludo.tsx#L20) and notice how the board vanishes while the game pieces are still in place.

2024-09-01 12:43 UTC, vibenedict commented on client/src/assets/images/Yellow white wall photo.jpg
Image is too large and will increase size of codebase :)
Please downscale to less than 250kb or replace with smaller image

2024-09-01 13:56 UTC, melnikga commented
Hey @vibenedict, is the task to replace only this square component?

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/9eebf8df-0fcc-4f0e-84e9-5a23471217a3">

2024-09-01 20:55 UTC, vibenedict commented on client/src/assets/images/Yellow white wall photo.jpg
@melnikga

2024-09-01 21:24 UTC, vibenedict requested changes
LGTM 

Please fix conflict so I can merge.
I think you just need to revert changes made to this file in order to fix the conflicts

2024-09-01 21:28 UTC, vibenedict requested changes

2024-09-01 21:28 UTC, vibenedict commented on onchain/manifests/dev/base/contracts/starkludo-GameActions-72b46dc4.toml
please revert change made to this file

2024-09-01 21:28 UTC, vibenedict commented on onchain/manifests/dev/base/contracts/starkludo-PlayerActions-20dad3ac.toml
please revert change made to this file

2024-09-01 21:28 UTC, vibenedict commented on onchain/manifests/dev/base/contracts/starkludo-actions-6e36eb0d.toml
please revert change made to this file

2024-09-02 18:30 UTC, vibenedict approved these changes
LGTM

2024-09-02 18:30 UTC, merged