Fix problem with commitlint workflow file #79 #86
sivicstudio/starkludo pull request #87
Opened 2024-10-02 14:38 UTC by GoSTEAN

## Description

- This PR resolves issue #79

2024-10-02 20:06 UTC, princeibs commented
Please update PR description according to the pull request template

2024-10-02 20:53 UTC, GoSTEAN commented
@princeibs I have updated the PR

2024-10-03 12:53 UTC, princeibs requested changes

2024-10-03 12:53 UTC, princeibs commented on client/.eslintrc.cjs
Please revert changes made to this file. The update you made is skipping all errors/warnings thereby making CI pass falsely.

2024-10-03 12:53 UTC, princeibs commented on client/package.json
I noticed you removed the flag: `--max-warnings 0`. Can you add it back?

2024-10-03 17:10 UTC, GoSTEAN commented on client/package.json
If I add it back it will make the workflow fail.

2024-10-04 13:00 UTC, merged